version: '2'

services:
  cache:
    container_name: nest_mq_redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '8379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
  
  service_booking:
    container_name: service_booking
    restart: on-failure
    build: ./backend
    env_file: ./env/backend/.env
    volumes:
      - ./src:/app/src
    ports:
      - "30000:3000"
    depends_on:
      - cache

  service_consumer:
    container_name: service_consumer
    restart: on-failure
    build: ./consumer
    env_file: ./env/consumer/.env
    volumes:
      - ./src:/app/src
    ports:
      - "31000:3001"
    depends_on:
      - cache

  service_notify:
    container_name: service_notify
    restart: on-failure
    build: ./socket_notify
    env_file: ./env/socket_notify/.env
    volumes:
      - ./src:/app/src
    ports:
      - "32000:3002"
    depends_on:
      - cache
  
  service_notify_io:
    container_name: service_notify_io
    restart: on-failure
    build: ./socket_io
    env_file: ./env/socket_io/.env
    volumes:
      - ./src:/app/src
    ports:
      - "33000:3003"
    depends_on:
      - cache

volumes:
  cache:
    driver: local